### ISSUE TITLE
Possible to modify prompt?

### ISSUE THREAD

**Issue by evanheckert** [vgaggia/JoyCaption-Extended-Un-Official#1]
This is fantastic, thanks for putting this together! 

I'm curious if you've played with the prompt and the language model used to significantly steer the attention or format of the captioning? 

I've been using [MNeMoNiCuZ/joy-caption-batch](https://github.com/MNeMoNiCuZ/joy-caption-batch/) before finding this repo, and when I use mlabonne/Meta-Llama-3.1-8B-Instruct-abliterated then changing the PROMPT value seems to nudge the wording very slightly, but it still mentions all the same properties.

**Comment by vgaggia** [comment]
I couldn't get the vlm prompt to effect the result, just like in that other repo, I'm not sure why to be honest.
